name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create Dockerfile
        run: docker build -t hardikagrawal2320/test .
      - name: Push Dockerfile
        run: docker push hardikagrawal2320/test 
      - name: Run Docker Image
        uses: open-fringecore/docker-ssh-push@v0.1.2-beta
        with:
            images: |
                hardikagrawal2320/test
            ssh-host: ${{ secrets.SSH_HOST }}
            ssh-user: ${{ secrets.SSH_USER }}
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}